# Generated by Django 4.0.2 on 2022-03-14 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('bmi', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=10)),
                ('exercise', models.CharField(max_length=20)),
                ('diabetic', models.CharField(max_length=10)),
                ('remark', models.CharField(default=None, max_length=50)),
                ('mealplan', models.CharField(default=None, max_length=50)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
