# Generated by Django 4.0.2 on 2022-03-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietician', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='bmi',
            field=models.IntegerField(default=0),
        ),
    ]
