# Generated by Django 4.0.2 on 2022-03-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietician', '0002_report_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
