# Generated by Django 4.0.2 on 2022-03-13 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietician', '0003_report_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
    ]
