# Generated by Django 4.0.2 on 2022-03-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietician', '0004_remove_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='mealplan',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
