# Generated by Django 4.0.2 on 2022-04-06 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_helper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='modification',
            new_name='modifications',
        ),
    ]
