# Generated by Django 4.0.2 on 2022-04-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedic_tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayurvedictips',
            name='description',
            field=models.TextField(),
        ),
    ]
