# Generated by Django 4.0.2 on 2022-03-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, default='defaultImg.png', upload_to='profile_pics'),
        ),
    ]
